#file: noinspection YAMLSchemaValidation
skirmish: –ú–∏–ª–æ—Ä–¥—ã, –Ω–µ –Ω–∞—á–∏–Ω–∞–π—Ç–µ —Å—Ä–∞—á –ø–æ–∂–∞–ª—É–π—Å—Ç–∞!
hello: –ü—Ä–∏–≤–µ—Ç, –¥–æ—Ä–æ–≥—É—à–∞!
start_here: –ù–∞—á–Ω–∏ –æ—Ç—Å—é–¥–∞:\nhttps://github.com/OldCodersClub/faq
start_video: –ò–ª–∏ –æ—Ç—Å—é–¥–∞:\nhttps://www.youtube.com/watch?v=_PfQvdDq_bY
message_links: –¢–∞–º –º–Ω–æ–≥–æ –ø–æ–ª–µ–∑–Ω—ã—Ö —Å—Å—ã–ª–æ–∫ –ø–æ–¥ –≤–∏–¥–µ–æ.
lariska_bot: –î–∞. –Ø –±–æ—Ç.\n–í–æ—Ç —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π:\nhttps://github.com/OldCodersClub/LariskaBot
forks: –ú–æ–∂–µ—Ç–µ —Ñ–æ—Ä–∫–∞—Ç—å, —Ä–µ–∫–≤–µ—Å—Ç–∏—Ç—å –∏ –¥–µ–ø–ª–æ–∏—Ç—å
photo_reply: –ö—Ä–∞—Å–∏–≤–µ–Ω—å–∫–æ üòç
flood_reply: –ü–æ–º–µ–¥–ª–µ–Ω–Ω–µ–µ, –¥–æ—Ä–æ–≥—É—à–∞!\n–Ø –∑–∞–ø–∏—Å—ã–≤–∞—é...
welcome: –ü—Ä–∏–≤–µ—Ç!\n–Ø –õ–∞—Ä–∏—Å–∫–∞ - –±–æ—Ç –∏–∑ –ö–ª—É–±–∞ –¥–µ–¥–æ–≤-–ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç–æ–≤.\n–í—Å–µ –º–æ–∏ –∫–æ–º–∞–Ω–¥—ã —Å–µ–∫—Ä–µ—Ç–Ω—ã–µ.\n–ò—Ö –º–æ–∂–Ω–æ —Ç–æ–ª—å–∫–æ –≤ —Ä–µ–ø–µ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å:\nhttps://github.com/OldCodersClub
